const Icon = ({ className, figure, size }) => (
  <i class={ `mark-icon icon-${size} ${className}` }>
    <span class={ className }>{ ICONS[figure] }</span></i>
);

const ICONS = {
  accept: '☑',
  alien: '👽',
  anchor: '⚓',
  arrow: '➹',
  atom: '⚛',
  automovil: '🚘',
  baby: '🚼',
  ballot: '྾',
  beach: '⛱',
  bellhopBell: '🛎',
  bicycle: '🚲',
  biohazard: '☣',
  bird: '🐦',
  boat: '⛵',
  bomb: '💣',
  book: '📚',
  bus: '🚍',
  calendar: '🗓',
  cat: '🐈',
  check: '✓',
  chili: '🌶',
  chore: '⚙',
  church: '⛪',
  creditCard: '💳',
  classicalBuilding: '🏛',
  clock: '🕒',
  circle: '◯',
  closed: '⛔',
  cloud: '☁',
  cloudy: '⛅',
  coffee: '☕',
  comet: '☄️',
  Construction: '🏗',
  crossMark: '❌',
  dagger: '🗡',
  dog: '🐕',
  dove: '🕊',
  diamond: '◇',
  eject: '⏏',
  eye: '👁',
  eyeGlass: '👓',
  factory: '🏭',
  family: '👪',
  femaleSign: '♀',
  ferry: '⛴',
  film: '🎞',
  finance: '💹',
  food: '🍽',
  framedPicture: '🖼',
  fuelPump: '⛽',
  globeAfrica: '🌍',
  globeAmerica: '🌎',
  globeAustralia: '🌏',
  graduationCap: '🎓',
  hammer: '⚒',
  hashtag: '𐄹',
  health: '☤',
  hearth: '❤',
  headphone: '🎧',
  helm: '⎈',
  hexagon: '⎔',
  home: '🏠',
  hourglass: '⌛',
  hourglass2: '⏳',
  houses: '🏘',
  inbox: '📥',
  island: '🏝',
  film: '🎬',
  flag: '⚑',
  fog: '🌫',
  label: '🏷',
  laptop: '💻',
  liftWeights: '🏋',
  link: '☍',
  lock: '🔒',
  mailbox: '📭',
  maleSign: '♂',
  men: '🚹',
  militaryMedal: '🎖',
  monkey: '🐵',
  moneyBag: '💰',
  mountain: '🏔',
  noSmoing: '🚭',
  note: '♫',
  oilDrum: '🛢',
  oldKey: '🗝',
  outbox: '📤',
  passengerShip: '🛳',
  pause: '⏸',
  peace: '☮',
  pencil: '✎',
  pentagon: '⬠',
  performingArts: '🎭',
  pick: '⛏',
  policeCar: '🚔',
  radioactive: '☢',
  railway: '🛤',
  ray: '⚡',
  record: '⏺',
  recycle: '♻',
  reject: '☒',
  repair: '🛠',
  scales: '⚖',
  search: '🔍',
  shield: '🛡',
  shoppingBags: '🛍',
  skull: '☠',
  snowflake: '❄',
  snowman: '⛄',
  speaker: '🔈',
  speakerDisable: '🔇',
  speakerSound: '🔉',
  speechBubble: '🗨',
  stop: '⏹',
  sparkles: '✨',
  spider: '🕷',
  spiderWeb: '🕸',
  spinner: '⚙',
  star: '★',
  storm: '🌧',
  sun: '☀',
  sun2: '☼',
  surf: '🏄',
  swim: '🏊',
  swords: '⚔',
  tent: '⛺',
  telephone: '☎️',
  telephoneLocation: '✆',
  temperature: '🌡',
  tickets: '🎟',
  thunder: '🌩',
  thunderstorm: '⛈',
  tornado: '🌪',
  triangle: '△',
  trophy: '🏆',
  umbrella: '☂',
  umbrellaWRain: '☔',
  unlock: '🔓',
  videoGame: '🎮',
  warning: '⚠',
  wastebasket: '🗑',
  wheelchair: '♿',
  women: '🚺',
  workerHelmet:'⛑️',
  worldMap: '🗺'
};

export default Icon;
